import Head from "next/head";
import { ContentsBody } from "../../components/contentns/Body";
import styles from "../../styles/Home.module.css";

export default function Contents() {
  return (
    <>
      <Head>
        <title>Eno Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/flash_lightning_ray_icon_231454.ico" />
      </Head>
      <main className={styles.main}>
        <ContentsBody />
      </main>
    </>
  );
}
